import { AppData, DEFAULT_CHECKLIST_ITEMS } from "@/types";

const createDefaultChecklist = (completedIndices: number[]) => {
  return DEFAULT_CHECKLIST_ITEMS.map((item, idx) => ({
    id: `chk-def-${idx}-${Date.now()}`,
    title: item,
    completed: completedIndices.includes(idx),
  }));
};

export const initialData: AppData = {
  students: [
    {
      id: "student-1",
      name: "Mira Yılmaz",
      username: "mira",
      password: "123",
      avatarColor: "from-pink-500 to-rose-500",
      targetUniversity: "Oxford / Imperial College",
      targetMajor: "Biomedical Engineering",
      phone: "+90 555 123 45 67",
      applications: [
        {
          id: "app-1",
          universityName: "University of Oxford",
          program: "Biomedical Engineering (MEng)",
          country: "İngiltere 🇬🇧",
          status: "hazirlaniyor",
          deadline: "2026-10-15",
        },
        {
          id: "app-2",
          universityName: "Imperial College London",
          program: "Biomedical Engineering with Management",
          country: "İngiltere 🇬🇧",
          status: "hazirlaniyor",
          deadline: "2027-01-15",
        },
        {
          id: "app-3",
          universityName: "KU Leuven",
          program: "Engineering Technology",
          country: "Belçika 🇧🇪",
          status: "beklemede",
          deadline: "2027-03-01",
        },
      ],
      checklist: createDefaultChecklist([0, 1, 2, 3, 6]), // Passport, Diploma, Transcript, English Proficiency, Motivation Letter
      createdAt: "2026-08-15T10:00:00.000Z",
    },
    {
      id: "student-2",
      name: "Bedirhan Çelik",
      username: "bedirhan",
      password: "123",
      avatarColor: "from-blue-500 to-cyan-500",
      targetUniversity: "TU Munich / ETH Zurich",
      targetMajor: "Computer Science",
      phone: "+90 555 234 56 78",
      applications: [
        {
          id: "app-4",
          universityName: "Technical University of Munich (TUM)",
          program: "Informatics / Computer Science (B.Sc.)",
          country: "Almanya 🇩🇪",
          status: "hazirlaniyor",
          deadline: "2027-05-31",
        },
        {
          id: "app-5",
          universityName: "ETH Zurich",
          program: "Computer Science",
          country: "İsviçre 🇨🇭",
          status: "hazirlaniyor",
          deadline: "2027-04-30",
        },
        {
          id: "app-6",
          universityName: "Delft University of Technology (TU Delft)",
          program: "Computer Science and Engineering",
          country: "Hollanda 🇳🇱",
          status: "beklemede",
          deadline: "2027-01-15",
        },
      ],
      checklist: createDefaultChecklist([0, 1, 2, 4, 8, 11]), // Passport, Diploma, Transcript, SAT, CV, Extra Curricular
      createdAt: "2026-08-16T11:30:00.000Z",
    },
    {
      id: "student-3",
      name: "Burak Demir",
      username: "burak",
      password: "123",
      avatarColor: "from-emerald-500 to-teal-500",
      targetUniversity: "University of Toronto",
      targetMajor: "Economics / Data Science",
      phone: "+90 555 345 67 89",
      applications: [
        {
          id: "app-7",
          universityName: "University of Toronto",
          program: "Economics and Data Analysis",
          country: "Kanada 🇨🇦",
          status: "hazirlaniyor",
          deadline: "2027-01-12",
        },
        {
          id: "app-8",
          universityName: "Bocconi University",
          program: "Economics, Management and Computer Science",
          country: "İtalya 🇮🇹",
          status: "beklemede",
          deadline: "2027-02-05",
        },
      ],
      checklist: createDefaultChecklist([0, 1, 2, 3, 7]), // Passport, Diploma, Transcript, English Proficiency, Recommendation Letter
      createdAt: "2026-08-17T09:15:00.000Z",
    },
  ],
  exams: [
    {
      id: "exam-1",
      studentId: "student-1",
      studentName: "Mira Yılmaz",
      title: "IELTS Academic",
      type: "IELTS",
      subType: "Computer-delivered",
      examDate: "2026-10-18",
      examTime: "09:00",
      location: "British Council - Maslak Test Merkezi",
      targetScore: "7.5 (L:8, R:8, W:7, S:7)",
      currentScore: "",
      registrationStatus: "registered",
      alarms: [30, 14, 7, 3, 1, 0],
      mockScores: [
        { id: "mock-1", date: "2026-08-20", score: "6.5", note: "İlk genel deneme" },
        { id: "mock-2", date: "2026-08-28", score: "7.0", note: "Reading 7.5, Writing 6.5" },
      ],
      createdAt: "2026-08-20T12:00:00.000Z",
      updatedAt: "2026-08-28T14:30:00.000Z",
    },
    {
      id: "exam-2",
      studentId: "student-1",
      studentName: "Mira Yılmaz",
      title: "AP Calculus BC",
      type: "AP",
      subType: "Calculus BC",
      examDate: "2026-05-12",
      examTime: "08:00",
      location: "Özel Okul Sınav Merkezi",
      targetScore: "5",
      currentScore: "",
      registrationStatus: "planned",
      alarms: [60, 30, 14, 7, 1],
      mockScores: [],
      createdAt: "2026-08-22T10:00:00.000Z",
      updatedAt: "2026-08-22T10:00:00.000Z",
    },
    {
      id: "exam-3",
      studentId: "student-2",
      studentName: "Bedirhan Çelik",
      title: "Digital SAT",
      type: "SAT",
      subType: "Official Test",
      examDate: "2026-11-07",
      examTime: "08:30",
      location: "Robert Kolej Sınav Merkezi",
      targetScore: "1520+ (Math: 790, ERW: 730)",
      currentScore: "",
      registrationStatus: "registered",
      alarms: [30, 14, 7, 3, 1, 0],
      mockScores: [
        { id: "mock-3", date: "2026-08-15", score: "1420", note: "Bluebook Test 1" },
        { id: "mock-4", date: "2026-08-25", score: "1480", note: "Bluebook Test 2 (Math 770)" },
      ],
      createdAt: "2026-08-16T14:00:00.000Z",
      updatedAt: "2026-08-25T16:00:00.000Z",
    },
    {
      id: "exam-4",
      studentId: "student-2",
      studentName: "Bedirhan Çelik",
      title: "AP Physics 1: Algebra-Based",
      type: "AP",
      subType: "Physics 1",
      examDate: "2026-05-15",
      examTime: "12:00",
      location: "Özel Okul Sınav Merkezi",
      targetScore: "5",
      currentScore: "",
      registrationStatus: "planned",
      alarms: [60, 30, 14, 7, 1],
      mockScores: [],
      createdAt: "2026-08-20T11:00:00.000Z",
      updatedAt: "2026-08-20T11:00:00.000Z",
    },
    {
      id: "exam-5",
      studentId: "student-3",
      studentName: "Burak Demir",
      title: "TOEFL iBT",
      type: "TOEFL",
      subType: "Home Edition / Test Center",
      examDate: "2026-10-24",
      examTime: "10:00",
      location: "Kadir Has Üniversitesi Test Merkezi",
      targetScore: "105+ (R:28, L:28, S:24, W:25)",
      currentScore: "",
      registrationStatus: "registered",
      alarms: [30, 14, 7, 3, 1, 0],
      mockScores: [
        { id: "mock-5", date: "2026-08-18", score: "98", note: "Genel deneme" },
      ],
      createdAt: "2026-08-18T15:00:00.000Z",
      updatedAt: "2026-08-18T15:00:00.000Z",
    },
  ],
};
